/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "on-secondary": "#ffffff",
                "tertiary-fixed": "#e5e2d8",
                "primary-container": "#006837",
                "on-surface": "#1b1c1c",
                "inverse-primary": "#83d99c",
                "surface-container-high": "#eae7e7",
                "on-surface-variant": "#3f4940",
                "tertiary-fixed-dim": "#c9c7bc",
                "secondary-fixed-dim": "#e9c349",
                "on-primary-container": "#8ee4a6",
                "on-secondary-fixed-variant": "#574500",
                "primary-fixed": "#9ef6b6",
                "outline-variant": "#bec9be",
                "inverse-on-surface": "#f3f0f0",
                "primary": "#004d27",
                "secondary-container": "#fed65b",
                "secondary": "#735c00",
                "on-error-container": "#93000a",
                "on-primary-fixed": "#00210e",
                "surface-container-lowest": "#ffffff",
                "tertiary": "#43433b",
                "on-background": "#1b1c1c",
                "on-tertiary-fixed-variant": "#48473f",
                "outline": "#6f7a70",
                "inverse-surface": "#303030",
                "surface-container": "#f0eded",
                "background": "#fcf9f8",
                "on-primary-fixed-variant": "#00522a",
                "on-tertiary-fixed": "#1c1c15",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "surface-variant": "#e4e2e1",
                "surface": "#fcf9f8",
                "surface-container-low": "#f6f3f2",
                "error": "#ba1a1a",
                "surface-container-highest": "#e4e2e1",
                "surface-bright": "#fcf9f8",
                "on-secondary-container": "#745c00",
                "surface-dim": "#dcd9d9",
                "surface-tint": "#0b6d3b",
                "secondary-fixed": "#ffe088",
                "tertiary-container": "#5b5a52",
                "on-tertiary": "#ffffff",
                "primary-fixed-dim": "#83d99c",
                "on-tertiary-container": "#d4d1c7",
                "on-secondary-fixed": "#241a00",
                "error-container": "#ffdad6",
                "accent": {
                    "gold": "#d4af37",
                    "amber": "#f59e0b"
                },
                "foundation": {
                    "bg": "#fbf9f8",
                    "surface": "#ffffff",
                    "border": "#e2e8f0",
                    "text": "#1e293b",
                    "muted": "#64748b"
                }
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "gutter": "24px",
                "margin-desktop": "40px",
                "unit": "8px",
                "margin-mobile": "16px",
                "container-max": "1280px"
            },
            fontFamily: {
                "body-sm": ["Inter", "sans-serif"],
                "headline-md": ["Plus Jakarta Sans", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
                "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
                "sans": ["Inter", "sans-serif"],
            },
            fontSize: {
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
                "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
            }
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
};
